version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-voip
    environment:
      MYSQL_ROOT_PASSWORD: voip
      MYSQL_DATABASE: voipdb
      MYSQL_USER: voipuser
      MYSQL_PASSWORD: voip
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
